### ISSUE TITLE
Can use job container instead of spinning up pods

### ISSUE THREAD

**Issue by nqminhuit** [nqminhuit/gis-stress-test#14]
https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container

delegate 
```yaml
  - name: gitbucket
    image: ghcr.io/gitbucket/gitbucket:4.39.0
    ports:
    - containerPort: 8080
      hostPort: 9898
```
from `*_dataset.yaml` to github workflow
